/*
 * TRY IT ON — STORY BANK
 *
 * This file contains the conversation content only.
 * You can add/edit stories here without touching the page UI.
 *
 * Each scene has a context and several variants. The app chooses a
 * different variant whenever you press "Another scene".
 */

const SLOTS = {
  drink: ["an oat milk latte", "a cold brew", "a matcha latte", "a chai latte", "an iced americano", "a hot chocolate"],
  snack: ["a croissant", "a blueberry muffin", "a cinnamon roll", "a bagel with cream cheese", "a scone"],
  dayLooking: ["Tuesday", "the weekend", "Wednesday", "Friday", "this morning"],
  activity: ["trivia night", "a movie", "board games", "something outdoorsy", "brunch"],
  stressor: ["work deadlines", "moving apartments", "wedding planning", "a big job hunt", "training for a race"],
  newActivity: ["pottery", "rock climbing", "learning guitar", "running", "cooking classes"],
  hobby: ["pottery", "trivia", "rock climbing", "running", "painting", "chess"],
  hangout: ["coffee", "lunch", "dinner", "a walk", "a proper catch-up"],
  newsItem: ["that new restaurant downtown", "Jamie’s big move", "the reunion everyone’s planning", "that show everyone’s binging", "the new place on Main Street"],
  priorJob: ["marketing", "retail management", "freelance design", "customer support", "teaching"],
  reasonForJob: ["the team culture", "the mission", "the flexibility", "the growth opportunities", "the people I met interviewing"],
  officeHazard: ["the third-floor printer", "the coffee after 3pm", "reply-all emails", "the break room microwave", "the office playlist"],
  chore: ["the dishes", "the laundry", "vacuuming", "the recycling", "the grocery shopping"],
  chore2: ["walking the dog", "answering some emails", "a nap", "returning some calls", "finishing my coffee"],
  timeSlot: ["on Friday", "Saturday night", "Sunday afternoon", "tonight", "this weekend"],
  thirdParty: ["Jordan", "Alex", "Sam", "Priya", "Marcus"],
  snackFood: ["pizza", "cookies", "chips", "ice cream", "cake"],
  meetDay: ["Saturday", "Sunday", "Friday night", "tomorrow", "next weekend"],
  meetTime: ["7", "6:30", "8ish", "5:45", "noon"],
  weekday: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  careerFocus: ["strategic", "creative", "hands-on", "collaborative", "leadership"],
  trait: ["work well under pressure", "love solving problems", "pick things up quickly", "pay attention to detail", "work well with a team", "stay calm when things get hectic"],
  growthArea: ["delegating more", "public speaking", "saying no to extra projects", "getting better at documentation", "not micromanaging myself"],
  timeframe: ["six months", "the first year", "90 days", "the first quarter", "a year"],
  successMetric: ["leading your own projects", "being fully ramped up with the team", "contributing to key decisions", "mentoring newer hires", "owning a full workstream"],
  concernTopic: ["the team’s current workload", "how remote work is handled", "the timeline for this role", "the team structure", "growth opportunities here"],
  field: ["marketing", "software", "teaching", "healthcare", "design", "finance"],
  relative: ["your cousin", "your uncle", "your brother", "your aunt", "your grandma"],
  occasion: ["the holidays", "Thanksgiving", "the family reunion", "my birthday", "the Fourth of July"],
  dish: ["grilled salmon", "mushroom risotto", "veggie burger", "pad thai", "roasted chicken"],

  // Additional slots used by the newer scenes.
  weather: ["pouring rain", "a heat wave", "that weird windy weather", "the first really cold morning", "perfect sunny weather"],
  place: ["the bookstore", "the park", "the museum", "the little café downtown", "the farmer’s market"],
  object: ["a ridiculous mug", "a tiny plant", "an old camera", "a bright red jacket", "a completely unnecessary lamp"],
  food: ["dumplings", "ramen", "tacos", "pancakes", "fresh bread"],
  game: ["Codenames", "Mario Kart", "a card game", "charades", "a ridiculously complicated board game"],
  errand: ["pick up a package", "return a shirt", "buy toothpaste", "get groceries", "drop something off"],
  excuse: ["I missed the bus", "my phone died", "I took a wrong turn", "I got distracted by a dog", "I underestimated how far away it was"],
  compliment: ["your jacket", "your haircut", "your shoes", "your taste in music", "your laugh"],
  surprise: ["I got tickets", "I found the thing you were looking for", "I actually remembered your coffee order", "I brought snacks", "I have a ridiculous story"],
  destination: ["the coast", "the mountains", "the next city over", "a tiny town nobody’s heard of", "somewhere with absolutely no itinerary"],
  excuse2: ["I was trying to be early", "I genuinely thought it was tomorrow", "I forgot where I parked", "I got trapped talking to someone", "I followed the wrong group"],
  weatherPlan: ["go for a walk", "sit outside", "check out the market", "take the scenic route", "find somewhere with good coffee"]
};

const scenarios = [
  {
    context: "Coffee shop regular",
    variants: [
      [
        ["Barista", "Hey, {name}. You’re early."],
        ["You", "That sounds accusatory."],
        ["Barista", "I’m impressed. Usually you arrive exactly when the line gets terrible."],
        ["You", "I like to live dangerously."],
        ["Barista", "The usual?"],
        ["You", "Actually, surprise me. {drink} maybe?"],
        ["Barista", "Bold choice. And food?"],
        ["You", "I’m pretending I came here for the coffee, but yes, {snack}."],
        ["Barista", "Thank you for being honest."],
        ["You", "How’s your {weekday} going?"],
        ["Barista", "Ask me after I’ve made approximately twenty-seven more drinks."],
        ["You", "So that’s a no."],
        ["Barista", "That’s a strong maybe."],
        ["You", "Fair enough."],
        ["Barista", "Here you go, {name}. Try not to let {activity} ruin the rest of your day."],
        ["You", "No promises."],
        ["Barista", "I never get promises from you anyway."],
        ["You", "Yet you keep serving me."],
        ["Barista", "Occupational hazard."],
        ["You", "See you tomorrow, probably." ]
      ],
      [
        ["Barista", "Morning, {name}. I have a question."],
        ["You", "That’s ominous."],
        ["Barista", "Why do you always stare at the menu like it personally offended you?"],
        ["You", "Because every morning I forget how coffee works."],
        ["Barista", "You’ve ordered the same thing for six months."],
        ["You", "That has never stopped me from considering my options."],
        ["Barista", "Fine. What are we considering?"],
        ["You", "{drink} and {snack}."],
        ["Barista", "A truly groundbreaking decision."],
        ["You", "Thank you for respecting my process."],
        ["Barista", "I’m trying."],
        ["You", "Anything exciting happen today?"],
        ["Barista", "Someone tried to order a cappuccino with no milk."],
        ["You", "How did you respond?"],
        ["Barista", "I stared at them until they reconsidered."],
        ["You", "Powerful."],
        ["Barista", "Anyway, here’s your coffee."],
        ["You", "You remembered."],
        ["Barista", "Of course I remembered, {name}."],
        ["You", "Okay, that’s actually very sweet." ]
      ],
      [
        ["Barista", "Hey, {name}. You look like you lost an argument with your alarm clock."],
        ["You", "I did. It was a decisive defeat."],
        ["Barista", "The coffee may be able to help."],
        ["You", "Please make that a legally binding statement."],
        ["Barista", "What’ll it be?"],
        ["You", "{drink}. And {snack}, because apparently I’m capable of planning ahead after all."],
        ["Barista", "I’m proud of you."],
        ["You", "Thank you. I’ve been working on myself."],
        ["Barista", "Huge day?"],
        ["You", "I’ve got {activity} later, and I’d like to arrive with at least one functional brain cell."],
        ["Barista", "Then we have a mission."],
        ["You", "We do."],
        ["Barista", "How much encouragement do you need?"],
        ["You", "A dangerous amount."],
        ["Barista", "Good. Here’s your order."],
        ["You", "You’re a lifesaver."],
        ["Barista", "Come back tomorrow and I’ll deny ever hearing that."],
        ["You", "Deal." ]
      ]
    ]
  },

  {
    context: "Catching up with an old friend",
    variants: [
      [
        ["Friend", "{name}! Oh my gosh."],
        ["You", "Hi! It has been way too long."],
        ["Friend", "I was literally just thinking, ‘I wonder what happened to you.’"],
        ["You", "Mostly? {stressor}."],
        ["Friend", "Ah. So you chose chaos."],
        ["You", "Apparently."],
        ["Friend", "Are you still doing {hobby}?"],
        ["You", "Of course. I have standards."],
        ["Friend", "That is not what I remember."],
        ["You", "I’ve evolved."],
        ["Friend", "Clearly."],
        ["You", "What about you?"],
        ["Friend", "I started {newActivity}."],
        ["You", "You? Voluntarily?"],
        ["Friend", "Exactly. I’m becoming interesting."],
        ["You", "I’m proud of you."],
        ["Friend", "We need to stop doing this once every geological era."],
        ["You", "Agreed."],
        ["Friend", "{hangout}. Soon."],
        ["You", "Soon. I mean it this time." ]
      ],
      [
        ["Friend", "Wait. Is that actually you, {name}?"],
        ["You", "I have been asking myself the same question."],
        ["Friend", "You look exactly the same."],
        ["You", "That’s either a compliment or a threat."],
        ["Friend", "Definitely a compliment."],
        ["You", "I’ll take it."],
        ["Friend", "So what’s new?"],
        ["You", "I got really into {newActivity}. It happened by accident."],
        ["Friend", "Of course it did."],
        ["You", "What is that supposed to mean?"],
        ["Friend", "You collect hobbies the way other people collect mugs."],
        ["You", "That is a very unfair comparison."],
        ["Friend", "Is it?"],
        ["You", "Yes."],
        ["Friend", "Okay. What’s your current favorite?"],
        ["You", "{hobby}."],
        ["Friend", "Yep. Still predictable."],
        ["You", "And yet you missed me."],
        ["Friend", "Unfortunately, yes." ]
      ]
    ]
  },

  {
    context: "First day at a new job",
    variants: [
      [
        ["Coworker", "You must be {name}. Welcome! I’m your unofficial tour guide."],
        ["You", "Unofficial? Should I be worried?"],
        ["Coworker", "Only about my sense of direction."],
        ["You", "Good start."],
        ["Coworker", "Coffee machine first. Everything else can wait."],
        ["You", "Finally, someone with priorities."],
        ["Coworker", "Where were you before this, {name}?"],
        ["You", "I was doing {priorJob}, then decided I needed a change."],
        ["Coworker", "And this place won you over?"],
        ["You", "Mostly {reasonForJob}."],
        ["Coworker", "Yeah, that got me too."],
        ["You", "I’m trying not to look too lost."],
        ["Coworker", "Don’t bother. Everyone looks lost on day one."],
        ["You", "That is strangely reassuring."],
        ["Coworker", "One more rule: never volunteer to fix {officeHazard}."],
        ["You", "Now I definitely want to know why."],
        ["Coworker", "Give it a week."],
        ["You", "Deal. I’ll ask you then."]
      ],
      [
        ["Coworker", "Morning! You’re {name}, right?"],
        ["You", "Yep. First day."],
        ["Coworker", "I know. You have the first-day look."],
        ["You", "Is it that obvious?"],
        ["Coworker", "Only because I had it last month."],
        ["You", "Excellent. At least I’m in good company."],
        ["Coworker", "Come on, I’ll show you your desk."],
        ["You", "Before I get lost?"],
        ["Coworker", "Exactly before you get lost."],
        ["You", "Thanks. So what’s the one thing I should know?"],
        ["Coworker", "The calendar is lying to you."],
        ["You", "That’s ominous."],
        ["Coworker", "If something says thirty minutes, assume an hour."],
        ["You", "Noted."],
        ["Coworker", "Also, lunch on {weekday}. We all go."],
        ["You", "That’s easy enough."],
        ["Coworker", "Great. You’re already learning."],
        ["You", "I think I can survive this place."]
      ]
    ]
  },

  {
    context: "Living with a roommate",
    variants: [
      [
        ["Roommate", "{name}, did you eat my {snackFood}?"],
        ["You", "Define ‘eat.’"],
        ["Roommate", "That is the worst possible answer."],
        ["You", "Okay, yes. I did."],
        ["Roommate", "It had my name on it."],
        ["You", "In fairness, the handwriting was tiny."],
        ["Roommate", "You’re replacing it."],
        ["You", "Obviously."],
        ["Roommate", "And while you’re up, did you ever do {chore}?"],
        ["You", "I was going to."],
        ["Roommate", "When?"],
        ["You", "Eventually."],
        ["Roommate", "Your definition of eventually is terrifying."],
        ["You", "I’ll do it tonight."],
        ["Roommate", "Fine. Also, are we still doing {activity} {timeSlot}?"],
        ["You", "Yes. I actually remembered."],
        ["Roommate", "Miracles really are happening today."],
        ["You", "I contain multitudes."]
      ],
      [
        ["Roommate", "Why is there a bowl in the living room?"],
        ["You", "Long story."],
        ["Roommate", "I have time."],
        ["You", "I started {chore2}, got distracted, and somehow ended up here."],
        ["Roommate", "That’s not a story. That’s a cry for help."],
        ["You", "A very productive cry for help."],
        ["Roommate", "Did you at least buy {snackFood}?"],
        ["You", "No, but I can."],
        ["Roommate", "Good. Peace offering accepted."],
        ["You", "So we’re good?"],
        ["Roommate", "We’re good if you also promise to do {chore}."],
        ["You", "You’re really committed to the chore agenda."],
        ["Roommate", "Someone has to be."],
        ["You", "Fine. After {activity}."],
        ["Roommate", "We’re actually still doing that?"],
        ["You", "Absolutely."],
        ["Roommate", "Okay. Then I’ll let the bowl stay mysterious for now."],
        ["You", "Thank you for your trust."]
      ]
    ]
  },

  {
    context: "A text thread",
    variants: [
      [
        ["Friend (text)", "hey {name} you doing anything {timeSlot}?"],
        ["You (text)", "depends why"],
        ["Friend (text)", "couple people are getting together for {activity}"],
        ["You (text)", "who’s going"],
        ["Friend (text)", "{thirdParty} lol"],
        ["You (text)", "oh no"],
        ["Friend (text)", "that bad?"],
        ["You (text)", "not bad. just statistically unpredictable"],
        ["Friend (text)", "you’re coming though"],
        ["You (text)", "probably"],
        ["Friend (text)", "good because I’m bringing {snackFood}"],
        ["You (text)", "okay now I’m definitely coming"],
        ["Friend (text)", "knew that would work"],
        ["You (text)", "what time"],
        ["Friend (text)", "around {meetTime}"],
        ["You (text)", "and where"],
        ["Friend (text)", "I’ll send it"],
        ["You (text)", "deal. don’t let {thirdParty} choose the music"]
      ],
      [
        ["Friend (text)", "urgent question"],
        ["You (text)", "what"],
        ["Friend (text)", "are you free {meetDay}"],
        ["You (text)", "maybe. why"],
        ["Friend (text)", "I need someone willing to commit to {activity}"],
        ["You (text)", "that sounds suspiciously like work"],
        ["Friend (text)", "it is not work"],
        ["You (text)", "then probably yes"],
        ["Friend (text)", "excellent"],
        ["You (text)", "who else"],
        ["Friend (text)", "{thirdParty} and a few others"],
        ["You (text)", "interesting lineup"],
        ["Friend (text)", "don’t overthink it"],
        ["You (text)", "too late"],
        ["Friend (text)", "bringing {snackFood} if that helps"],
        ["You (text)", "it does"],
        ["Friend (text)", "around {meetTime}?"],
        ["You (text)", "works. send details"]
      ]
    ]
  },

  {
    context: "A job interview",
    variants: [
      [
        ["Interviewer", "Thanks for coming in, {name}. How are you feeling?"],
        ["You", "A little nervous, but excited."],
        ["Interviewer", "That’s completely fair. Let’s start simple. Tell me about your background."],
        ["You", "I spent several years in {priorJob}, and lately I’ve wanted something more {careerFocus}."],
        ["Interviewer", "What drew you toward that change?"],
        ["You", "{reasonForJob}, mostly. I wanted work I could really care about."],
        ["Interviewer", "What do you think you bring to a team?"],
        ["You", "I {trait}."],
        ["Interviewer", "Can you give me an example?"],
        ["You", "Sure. There was one project where things went sideways, and I ended up..."],
        ["Interviewer", "That is exactly the sort of example I was looking for."],
        ["You", "Good."],
        ["Interviewer", "What are you still working on?"],
        ["You", "Probably {growthArea}. I’m getting better at it."],
        ["Interviewer", "That’s a thoughtful answer."],
        ["You", "Thank you."],
        ["Interviewer", "What would success look like after {timeframe}?"],
        ["You", "Being trusted with bigger pieces of the work and contributing without needing hand-holding."]
      ],
      [
        ["Interviewer", "Hi, {name}. Thanks for being here."],
        ["You", "Thanks for having me."],
        ["Interviewer", "I’ll skip the formal script. What interested you about this role?"],
        ["You", "The combination of the work itself and {reasonForJob}."],
        ["Interviewer", "What work have you done that feels most relevant?"],
        ["You", "I was in {priorJob}, where I learned how to {trait}."],
        ["Interviewer", "And what’s something you had to learn the hard way?"],
        ["You", "{growthArea}, definitely."],
        ["Interviewer", "That’s a common answer. What changed for you?"],
        ["You", "I stopped treating it like a weakness and started treating it like a skill I could practice."],
        ["Interviewer", "I like that framing."],
        ["You", "It took me a while to get there."],
        ["Interviewer", "Where would you hope to be after {timeframe}?"],
        ["You", "I’d like to be someone the team can rely on for difficult work."],
        ["Interviewer", "Good. Do you have questions for me?"],
        ["You", "Actually, yes. What does the team wish a new hire understood sooner?"],
        ["Interviewer", "Excellent question."],
        ["You", "I figured you’d know better than the job posting."]
      ]
    ]
  },

  {
    context: "Meeting someone at a party",
    variants: [
      [
        ["Someone new", "Hi. I don’t think we’ve met."],
        ["You", "I’m {name}. I don’t know many people here either."],
        ["Someone new", "Excellent. We can be confused together."],
        ["You", "Deal."],
        ["Someone new", "How do you know the host?"],
        ["You", "We used to work together. You?"],
        ["Someone new", "Friend of a friend, which apparently is enough to get invited."],
        ["You", "Sounds official."],
        ["Someone new", "So what do you do?"],
        ["You", "I’m in {field}. It keeps me busy."],
        ["Someone new", "And what do you do when you’re not busy?"],
        ["You", "Usually {hobby}."],
        ["Someone new", "Oh, actually? How did you get into that?"],
        ["You", "A friend dragged me into it once. I stayed."],
        ["Someone new", "That’s how all good hobbies happen."],
        ["You", "Maybe you should try it."],
        ["Someone new", "I might."],
        ["You", "Then I’ll expect a review."]
      ],
      [
        ["Someone new", "You look like you know where the snacks are."],
        ["You", "That’s the nicest compliment I’ve gotten tonight."],
        ["Someone new", "I’m serious."],
        ["You", "Then yes. Kitchen, left side."],
        ["Someone new", "Thank you. I’m Taylor."],
        ["You", "I’m {name}."],
        ["Someone new", "Nice to meet you, {name}."],
        ["You", "You too."],
        ["Someone new", "How do you know everyone here?"],
        ["You", "I don’t. That’s the trick."],
        ["Someone new", "Good, so it’s not just me."],
        ["You", "Definitely not."],
        ["Someone new", "What keeps you occupied?"],
        ["You", "{field}, mostly, and {hobby} when I need an excuse to stop thinking about work."],
        ["Someone new", "That sounds useful."],
        ["You", "It is until I start thinking about it too much."],
        ["Someone new", "I like your system."],
        ["You", "You should borrow it."]
      ],
      [
        ["Someone new", "Mind if I stand here? I needed a break from the loud room."],
        ["You", "Please. I was doing the exact same thing."],
        ["Someone new", "Perfect."],
        ["You", "I’m {name}, by the way."],
        ["Someone new", "Nice to meet you."],
        ["You", "You too."],
        ["Someone new", "What brought you here?"],
        ["You", "The promise of knowing at least two people."],
        ["Someone new", "And how many do you know now?"],
        ["You", "Still two."],
        ["Someone new", "Same."],
        ["You", "We’re doing great."],
        ["Someone new", "So what are you into?"],
        ["You", "Lately? {hobby}."],
        ["Someone new", "I’ve always wanted to try that."],
        ["You", "There’s a place nearby. You should come sometime."],
        ["Someone new", "I’d actually like that."],
        ["You", "Then let’s not lose each other in this party."]
      ]
    ]
  },

  {
    context: "A weekend call with Mom",
    variants: [
      [
        ["Mom", "Hi, honey. How’s your weekend going?"],
        ["You", "Pretty good. I finally have a little breathing room."],
        ["Mom", "Good. What have you been up to?"],
        ["You", "Mostly {stressor}, unfortunately."],
        ["Mom", "That sounds exhausting."],
        ["You", "It is, but I’m managing."],
        ["Mom", "You’re always ‘managing.’ Have you done anything fun?"],
        ["You", "I actually started looking into {newActivity}."],
        ["Mom", "Really? Since when?"],
        ["You", "Since I decided I needed a hobby that wasn’t work."],
        ["Mom", "I approve."],
        ["You", "How are things at home?"],
        ["Mom", "Good. {relative} has apparently become obsessed with {hobby}."],
        ["You", "No way."],
        ["Mom", "I know. I never saw that coming."],
        ["You", "Me neither."],
        ["Mom", "Are you coming for {occasion}?"],
        ["You", "I am. I wouldn’t miss it."]
      ],
      [
        ["Mom", "Hey, sweetie. Did I catch you at a bad time?"],
        ["You", "Nope. I was just deciding what to do with the rest of the day."],
        ["Mom", "Anything interesting?"],
        ["You", "Maybe {activity}. I haven’t decided."],
        ["Mom", "That sounds more fun than anything I’m doing."],
        ["You", "What are you doing?"],
        ["Mom", "Trying to organize the house while everyone else makes it worse."],
        ["You", "So, the usual."],
        ["Mom", "Exactly."],
        ["You", "How’s everybody?"],
        ["Mom", "Good. Your {relative} called earlier and told me all about {newActivity}."],
        ["You", "Of course they did."],
        ["Mom", "You two really do have that in common."],
        ["You", "Maybe that’s not a bad thing."],
        ["Mom", "No, it’s sweet."],
        ["You", "What are we doing for {occasion}?"],
        ["Mom", "Nothing huge. I just want everyone together."],
        ["You", "Then I’ll be there."]
      ],
      [
        ["Mom", "Hi, {name}. I was thinking about you."],
        ["You", "That’s nice. I was actually about to call."],
        ["Mom", "Then apparently we have good timing."],
        ["You", "How have you been?"],
        ["Mom", "Busy. There’s always something."],
        ["You", "What’s the something this week?"],
        ["Mom", "Getting ready for {occasion} and trying to keep everyone on schedule."],
        ["You", "How’s that working?"],
        ["Mom", "Badly."],
        ["You", "At least you’re honest."],
        ["Mom", "What about you?"],
        ["You", "I’m okay. I’ve been spending some time on {newActivity}."],
        ["Mom", "I like hearing you have something fun to do."],
        ["You", "Me too."],
        ["Mom", "Will you call before you make travel plans?"],
        ["You", "Of course."],
        ["Mom", "Good. I want to actually see you this time."],
        ["You", "You will. Promise."]
      ]
    ]
  },

  {
    context: "A spontaneous afternoon out",
    variants: [
      [
        ["Friend", "So. I have an idea."],
        ["You", "That sentence has caused problems before."],
        ["Friend", "This one is good."],
        ["You", "Go on."],
        ["Friend", "We go to {place}, get {food}, and refuse to check the time."],
        ["You", "That is a very good idea."],
        ["Friend", "I knew you’d understand."],
        ["You", "What if we get bored?"],
        ["Friend", "Then we invent something to do."],
        ["You", "What if it starts raining?"],
        ["Friend", "Then we become people who enjoy rain."],
        ["You", "You’ve planned this impressively little."],
        ["Friend", "Exactly."],
        ["You", "Alright. I’m in."],
        ["Friend", "Excellent. Let’s go before either of us becomes sensible."],
        ["You", "Too late. I brought a jacket."],
        ["Friend", "Unbelievable."]
      ],
      [
        ["Friend", "Do you have plans?"],
        ["You", "Not anymore."],
        ["Friend", "Perfect."],
        ["You", "Why does that sound like a trap?"],
        ["Friend", "Because I need you to accompany me on an extremely important mission."],
        ["You", "What kind?"],
        ["Friend", "We need to find the best {food} in town."],
        ["You", "You’re serious."],
        ["Friend", "Completely."],
        ["You", "Alright. I’ll help."],
        ["Friend", "Excellent."],
        ["You", "How many places are we trying?"],
        ["Friend", "As many as necessary."],
        ["You", "That is not a number."],
        ["Friend", "It is now."],
        ["You", "Okay, {name}. Lead on."]
      ]
    ]
  },

  {
    context: "A surprisingly good first date",
    variants: [
      [
        ["Date", "Hi. You’re {name}, right?"],
        ["You", "Yep. And you must be the person I was hoping actually existed."],
        ["Date", "Okay, that’s a strong opening."],
        ["You", "I’m trying to set expectations early."],
        ["Date", "I respect it."],
        ["You", "How nervous are you?"],
        ["Date", "About a six out of ten."],
        ["You", "That low?"],
        ["Date", "It was an eight until you made me laugh."],
        ["You", "I’ll take that as a win."],
        ["Date", "So what’s something I wouldn’t guess from your profile?"],
        ["You", "I’m weirdly competitive about {hobby}."],
        ["Date", "That is incredibly specific."],
        ["You", "I know."],
        ["Date", "I’m going to need evidence eventually."],
        ["You", "Eventually can be arranged."],
        ["Date", "Good. I like where this is going."],
        ["You", "Me too."]
      ],
      [
        ["Date", "I almost walked past you."],
        ["You", "Why? Do I not look like my pictures?"],
        ["Date", "No, you do. I just expected you to look more nervous."],
        ["You", "Oh, I’m nervous. I’m just hiding it professionally."],
        ["Date", "Impressive."],
        ["You", "Thank you."],
        ["Date", "What do you normally do on a weekend?"],
        ["You", "Usually {activity}, or convincing myself I’m going to be productive."],
        ["Date", "How often does the productivity happen?"],
        ["You", "I’d rather not disclose that."],
        ["Date", "Fair enough."],
        ["You", "What about you?"],
        ["Date", "I’m trying to get into {newActivity}."],
        ["You", "You’ll have to tell me how that goes."],
        ["Date", "I could tell you now."],
        ["You", "Now?"],
        ["Date", "If we get coffee again."],
        ["You", "I think I can make time for that."]
      ]
    ]
  },

  {
    context: "Planning a tiny road trip",
    variants: [
      [
        ["Friend", "Okay, important question: how much luggage are you bringing?"],
        ["You", "Define luggage."],
        ["Friend", "That answer scares me."],
        ["You", "I’m a light packer."],
        ["Friend", "You once brought three jackets for an overnight trip."],
        ["You", "There were different climates."],
        ["Friend", "It was one state over."],
        ["You", "Details."],
        ["Friend", "We’re driving to {destination}."],
        ["You", "Nice."],
        ["Friend", "And I want no itinerary."],
        ["You", "Now that is dangerous."],
        ["Friend", "We stop when we see something interesting."],
        ["You", "I love that."],
        ["Friend", "I knew you would."],
        ["You", "What’s the one rule?"],
        ["Friend", "No complaining about the playlist."],
        ["You", "I can’t promise that."],
        ["Friend", "Then we’re doomed."]
      ],
      [
        ["Friend", "I made the plan."],
        ["You", "That sentence is either comforting or terrifying."],
        ["Friend", "Comforting."],
        ["You", "Explain."],
        ["Friend", "We’re leaving Saturday morning, getting {food}, and ending up in {destination}."],
        ["You", "And the rest?"],
        ["Friend", "We’ll figure it out."],
        ["You", "You actually planned nothing."],
        ["Friend", "I planned the important part."],
        ["You", "The food?"],
        ["Friend", "Exactly."],
        ["You", "You know what? I’m convinced."],
        ["Friend", "Excellent."],
        ["You", "Can I control the music sometimes?"],
        ["Friend", "Absolutely not."],
        ["You", "Then I withdraw my support."],
        ["Friend", "Too late, {name}. You’re coming."],
        ["You", "Fine. I’m coming."]
      ]
    ]
  },

  {
    context: "An unexpectedly chaotic family dinner",
    variants: [
      [
        ["Relative", "{name}, you’re late."],
        ["You", "I’m not late. Dinner is early."],
        ["Relative", "That is not how time works."],
        ["You", "It is in this family."],
        ["Relative", "Come help me with the table."],
        ["You", "What happened to everyone else?"],
        ["Relative", "Someone forgot the bread, someone is arguing about music, and your {relative} is telling the same story again."],
        ["You", "Ah. So everything is normal."],
        ["Relative", "Exactly."],
        ["You", "What are we eating?"],
        ["Relative", "{dish}."],
        ["You", "Okay, suddenly this is worth being here for."],
        ["Relative", "Be nice."],
        ["You", "I am being nice."],
        ["Relative", "You called the seating arrangement ‘political.’"],
        ["You", "Because it is."],
        ["Relative", "Just sit down, {name}."],
        ["You", "Fine."],
        ["Relative", "And no starting arguments."],
        ["You", "I make no promises."]
      ],
      [
        ["Relative", "You made it!"],
        ["You", "Barely."],
        ["Relative", "What happened?"],
        ["You", "Long story."],
        ["Relative", "Give me the short version."],
        ["You", "{excuse}."],
        ["Relative", "That sounds exactly like something you would do."],
        ["You", "Thank you."],
        ["Relative", "That was not a compliment."],
        ["You", "I’m choosing to hear it as one."],
        ["Relative", "Come on, dinner’s ready."],
        ["You", "What did you make?"],
        ["Relative", "{dish}."],
        ["You", "Okay, now I’m glad I came."],
        ["Relative", "We were going to eat without you."],
        ["You", "Heartless."],
        ["Relative", "Hungry."],
        ["You", "Fair."]
      ]
    ]
  },

  {
    context: "First day on a new team",
    variants: [
      [
        ["Coworker", "You must be {name}. Welcome."],
        ["You", "Thanks. I’m still trying to figure out where everything is."],
        ["Coworker", "That takes about a month."],
        ["You", "Good. I have time."],
        ["Coworker", "Coffee’s over there. Snacks are hidden in the cabinet nobody labels."],
        ["You", "Important information."],
        ["Coworker", "You were doing {priorJob} before this, right?"],
        ["You", "Yep. I wanted something more {careerFocus}."],
        ["Coworker", "Then you picked an interesting place."],
        ["You", "Interesting good or interesting concerning?"],
        ["Coworker", "Ask me after you’ve met the calendar."],
        ["You", "The calendar?"],
        ["Coworker", "You’ll see."],
        ["You", "That is not reassuring."],
        ["Coworker", "You’ll be fine, {name}."],
        ["You", "I’m choosing to believe you."],
        ["Coworker", "Excellent. You’re already adapting."]
      ],
      [
        ["Coworker", "Hey, {name}. I’m supposed to show you around."],
        ["You", "Perfect. I have approximately twelve questions."],
        ["Coworker", "Good. Save the other twelve for tomorrow."],
        ["You", "I like your optimism."],
        ["Coworker", "Where were you before this?"],
        ["You", "{priorJob}."],
        ["Coworker", "And why leave?"],
        ["You", "Mostly {reasonForJob}."],
        ["Coworker", "Fair."],
        ["You", "Any rules I should know?"],
        ["Coworker", "Never touch {officeHazard}."],
        ["You", "You’re the second person to say that."],
        ["Coworker", "Then listen to the second person."],
        ["You", "Noted."],
        ["Coworker", "And come to the team lunch on {weekday}."],
        ["You", "That one I can handle."],
        ["Coworker", "Great. You’re officially one of us."]
      ]
    ]
  }
];
